### ISSUE TITLE
[RESEARCH] Docker/Docker compose

### ISSUE THREAD

**Issue by developerasun** [developerasun/myCodeBox-backend#89]
# topic : understanding doker compose in docker
## read this 
> Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a YAML file to configure your application’s services. Then, with a single command, you create and start all the services from your configuration. 

> Compose works in all environments: production, staging, development, testing, as well as CI workflows.

Using Compose is basically a three-step process:
1. Define your app’s environment with a Dockerfile so it can be reproduced anywhere.
1. Define the services that make up your app in docker-compose.yml so they can be run together in an isolated environment.
1. Run docker compose up and the Docker compose command starts and runs your entire app. You can alternatively run docker-compose up using the docker-compose binary.

```yaml
version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
```

### Multiple isolated environments on a single host
> Compose uses a project name to isolate environments from each other. You can make use of this project name in several different contexts:

> The default project name is the basename of the project directory. You can set a custom project name by using the -p command line option or the COMPOSE_PROJECT_NAME environment variable.

> The default project directory is the base directory of the Compose file. A custom value for it can be defined with the --project-directory command line option.

> Compose supports variables in the Compose file. You can use these variables to customize your composition for different environments, or different users

## reference
- [Docker : overview of docker compose](https://docs.docker.com/compose/)
